In [12]:
import pandas as pd
import numpy as np
import cvxpy as cv
import gurobipy

In [13]:
m=1000


dis=np.array([[m,10,40,30],
              [10,m,5,40],
              [40,5,m,20],
              [30,40,20,m]])

demand=np.array([5,10,15,10])
x=cv.Variable(dis.shape,boolean=True)

In [14]:

d=cv.Variable(4,integer=True )

  

In [15]:
u=cv.Variable(4,nonneg=True)
constraints= [cv.sum(x,axis=0)==1,cv.sum(x,axis=1)==1,u<=3,cv.sum(d)<=35]

#for i in range(4): 
    #constraints.append(u[i] >= 0)

In [16]:
Obj=cv.Minimize(cv.sum(cv.multiply(dis,x))-cv.sum(d))
#sum([dis[i,:]*x[:,i] for i in range(4)])


for i in range(1,4):
    for j in range(1,4):
        if i != j:
            constraints.append(u[i] - u[j] + 4*x[i,j] <= 3)
            

y=cv.Variable(4)
for i in range(4):
    constraints.append(y[i]==cv.sum(x,axis=1))

for i in range(4):
       constraints.append(demand[i]*y[i]>=d[i])  

  

In [17]:
constraints


[Equality(Expression(AFFINE, NONNEGATIVE, (4,)), Constant(CONSTANT, NONNEGATIVE, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, (4,)), Constant(CONSTANT, NONNEGATIVE, ())),
 Inequality(Variable((4,), nonneg=True)),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Equality(Expression(AFFINE, UNKNOWN, ()), Expression(AFFINE, NONNEGATIVE, (4,))),
 Equality(Expression(AFFINE, UNKNOWN, ()), Expression(AFFINE, NONNEGATIVE, (4,))),
 Equality(Expression(AFFINE, UNKNOWN, ()), Expression(AFFINE, NONNEGATIVE, (4,))),
 Equality(Expression(AFFINE, UNKNOWN, ()), Expression(AFFINE, NONNEGATIVE, (4,))),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Expression(AFFINE, UNKNOWN

In [28]:
PRB=cv.Problem(Obj,constraints)
#ECOS_BB, GLPK_MI
PRB.solve(solver=cv.GUROBI,verbose=True)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [19]:
r=x.value
r

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
d.value

array([ 0., 10., 15., 10.])

In [21]:
route=['1','-']
for i in range(4):
    for j in range(4):
        if r[i,j]==1:
             route.append(str(j)+' -')

In [22]:
cv.sum(demand@x)

Expression(AFFINE, NONNEGATIVE, ())

In [23]:
demand@x.value

array([10., 15., 10.,  5.])

In [24]:
print(cv.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'GUROBI', 'OSQP', 'SCS']


In [26]:
 PRB.solution

Solution(optimal, {1010: array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]]), 1011: array([ 0., 10., 15., 10.]), 1012: array([0., 3., 2., 0.]), 1103: array([1., 1., 1., 1.])}, {}, {})

In [27]:
cv.sum(cv.multiply(dis,dis)).value

4009250.0

In [ ]:

for i in range(1,4):
    for j in range(1,4):
      if i!=j:
         print(i+j) 